version: '3'

services:
  webserver:
    image: webdevops/php-apache-dev:8.1
    restart: always
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html
    ports:
      - 999:80
      - 445:443

    volumes:
      - ./:/var/www/html